### ISSUE TITLE
Can't search certain did:web profiles

### ISSUE THREAD

**Issue by luizzeroxis** [notjuliet/pdsls#5]
Hi, I tried looking up Lamp's profile (https://bsky.app/profile/lamp.wtf), but it says "Failed to construct 'URL': Invalid URL". I think it's because the .well-known/did.json file in their domain doesn't have the proper CORS headers, so you can't access it from PDSls. Not sure what the solution could be.

**Comment by notjuliet** [comment]
they have to set this themselves
`Access-Control-Allow-Origin:*`

**Comment by luizzeroxis** [comment]
Is there nothing that can be done on the tool itself?
