### ISSUE TITLE
Error: URL.canParse is not a function. (In 'URL.canParse(s)', 'URL.canParse' is undefined)

### ISSUE THREAD

**Issue by ledlamp** [notjuliet/pdsls#8]
![image](https://github.com/user-attachments/assets/e286c83d-1621-491f-9555-b030d0a7b943)

**Comment by notjuliet** [comment]
can you make sure your browser is updated to the latest version
this might be supported on a newer version

**Comment by ledlamp** [comment]
I can not update. iOS 16 is the latest for my iPhone 8. URL.canParse was added in iOS 17.

**Comment by notjuliet** [comment]
tell me if it works now
